# -*- coding: utf-8 -*-
"""st_DeFore_main.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pEM98bVwOHSZXm9aIAOi3ftp0UxZGrED
"""

import utils

def main(df, warehouse, pred_date):

  df = utils.pre_format(df)
  df = df[df['warehouse_agg'] == warehouse] 

  future = utils.create_prediction_range(df, pred_date)
  df, future = utils.add_main_feature(df), utils.add_main_feature(future)
  df, future = utils.add_twin_dates_feature(df), utils.add_twin_dates_feature(future)
  result = utils.prophet_model(df, future)
  
  return result